---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-cluster
  namespace: lena
spec:
  selector:
    matchLabels:
      name: was-cluster
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: was-cluster
    spec:
      containers:
      - name: was-cluster
        image: syhwang.harbor.com/spring-sample-maven/spring-sample:latest
        #livenessProbe:
        #  httpGet:
        #    path: /index.jsp
        #    port: 8180
        #  initialDelaySeconds: 20
        #  periodSeconds: 5
        #readinessProbe:
        #  httpGet:
        #    path: /index.jsp
        #    port: 8180
        #  initialDelaySeconds: 10
        #  periodSeconds: 3
        ports:
        - containerPort: 8180
        envFrom:
        - configMapRef:
            name: was-cluster-config
        - secretRef:
            name: was-cluster-secret
#        volumeMounts:
#        - name: lena-app-pv
#          mountPath: /usr/local/lena/servers/appServer/logs
#      volumes:
#        - name: lena-app-pv
#          persistentVolumeClaim:
#            claimName: lena-app-pvc
      terminationGracePeriodSeconds: 60
