---
apiVersion: v1
kind: ConfigMap
metadata:
  name: was-cluster-config
  namespace: lena
data:
  LENA_MANAGER_ADDRESS: "lena-manager.lena.svc.cluster.local:7700"
  LENA_MANAGER_MONITORING_PORT: "16100"
  LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
  LENA_CONFIG_TEMPLATE_ID: "was-cluster"
  LENA_LICENSE_DOWNLOAD_URL: "manager"
  #LENA_AGENT_RUN: "Y"
  JAVA_DOMAIN_CACHE_TTL: "3"