---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-cluster
  namespace: lena
spec:
  selector:
    matchLabels:
      name: was-cluster
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: was-cluster
    spec:
      containers:
      - name: was-cluster
        image: syhwang.harbor.com/spring-sample-maven/spring-sample:20260828-1332-2bd4152
        ports:
        - containerPort: 8180
        envFrom:
        - configMapRef:
            name: was-cluster-config
        - secretRef:
            name: was-cluster-secret
      terminationGracePeriodSeconds: 60
